### ISSUE TITLE
How to run a single  input RGB image?

### ISSUE THREAD

**Issue by mtbui2010** [chensong1995/HybridPose#43]
Hi Chen, 

Your work is impressive. Can you provide an example that depicts how to load the pre-trained network and execute it in a given RGB image? I tried to discover from train.py and evaluate.py, but I failed.

**Comment by weidu3** [comment]
Hi, have you solved this problem?

**Comment by chensong1995** [comment]
Hello weidu3,

Thank you for your interest in our work! My recommendation is to run:

`LD_LIBRARY_PATH=lib/regressor:$LD_LIBRARY_PATH python src/train_core.py --load_dir saved_weights/linemod/ape/checkpoints/0.001/199 --object_name ape`

Feel free to change `--load_dir` and `--object_name` as you wish. This command will skip the training (because the next epoch number 200 is the same as [the total number of epochs](https://github.com/chensong1995/HybridPose/blob/master/src/train_core.py#L25)) and invoke [this line](https://github.com/chensong1995/HybridPose/blob/master/src/train_core.py#L111) to evaluate on the testing split of the dataset. It is possible to create a new dataset class in [this directory](https://github.com/chensong1995/HybridPose/tree/master/lib/datasets) and use it in the evaluation. However, if your RGB image is very different from the training examples, you may have to re-train the network using your data to obtain a reasonable performance.

I hope this helps! Let me know if you have further concern.
